ALTER TABLE public.incidents
  ADD COLUMN IF NOT EXISTS user_id BIGINT,
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS lon DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'new';

ALTER TABLE public.incidents
  ALTER COLUMN category SET NOT NULL,
  ALTER COLUMN lat SET NOT NULL,
  ALTER COLUMN lon SET NOT NULL,
  ALTER COLUMN status SET DEFAULT 'new',
  ALTER COLUMN status SET NOT NULL;
